apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
type: Opaque
data:
  SMTP_SERVER: c2FuZGJveC5zbXRwLm1haWx0cmFwLmlv  # sandbox.smtp.mailtrap.io
  SMTP_USERNAME: MGE0YzkxNzk1YjllMjY=  # 0a4c91795b9e26
  SMTP_PASSWORD: YjdkKioqKjk5OGY=  # b7d****998f
  ADMIN_EMAIL: dGVzdEB0ZXN0LmNvbQ==  # test@test.com